services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:dev_password@db:5432/collective
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/ssl:/etc/nginx/ssl  # Mount SSL certificates (for updates without rebuild)
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=collective
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - ./db_prod:/var/lib/postgresql/data  # Separate volume for prod